---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: ND3mZpWrmpAEEjke2N7eJn65IrUPLtCxwYSaql1b0L0+LgaxMPik2Eb9DEYsNSV4SWC4FCOdKtsQ8IIangRYDQ==
  MSG_KEY: <`rake generate:msg_key`>
  REDIS_URL: <provision Redis instance; provide non-TLS URL for dev/test>

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: ND3mZpWrmpAEEjke2N7eJn65IrUPLtCxwYSaql1b0L0+LgaxMPik2Eb9DEYsNSV4SWC4FCOdKtsQ8IIangRYDQ==
  MSG_KEY: <`rake generate:msg_key`>
  REDIS_URL: <provision Redis instance; provide non-TLS URL for dev/test>

production:
  API_URL: <provisioned API URL (ending with api/[version])>
  APP_URL: <provisioned app URL (root without ending slash)>
  SESSION_SECRET: <`rake generate:session_secret`>
  MSG_KEY: <`rake generate:msg_key`>
  REDIS_URL: <provision Redis instance with TLS URL>
  REDIS_TLS_URL: <provision Redis instance with TLS URL>
