---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: ND3mZpWrmpAEEjke2N7eJn65IrUPLtCxwYSaql1b0L0+LgaxMPik2Eb9DEYsNSV4SWC4FCOdKtsQ8IIangRYDQ==
  MSG_KEY: Hb9DLQWSXyisHm8CArBXaIw9crv/wpKTVObm6u8xhxw=
  REDIS_URL: <provision Redis instance; provide non-TLS URL for dev/test>
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: <provision ID/SECRET on Github>
  GH_CLIENT_SECRET: <provision ID/SECRET on Github>

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: ND3mZpWrmpAEEjke2N7eJn65IrUPLtCxwYSaql1b0L0+LgaxMPik2Eb9DEYsNSV4SWC4FCOdKtsQ8IIangRYDQ==
  MSG_KEY: Hb9DLQWSXyisHm8CArBXaIw9crv/wpKTVObm6u8xhxw=
  REDIS_URL: <provision Redis instance; provide non-TLS URL for dev/test>
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: <provision ID/SECRET on Github>
  GH_CLIENT_SECRET: <provision ID/SECRET on Github>

production:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: <rake generate:session_secret>
  MSG_KEY: <rake generate:msg_key>
  REDIS_TLS_URL: <provision Redis instance; provide TLS rediss URL for production>
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: <provision ID/SECRET on Github>
  GH_CLIENT_SECRET: <provision ID/SECRET on Github>
